using System.Text;
using Microsoft.CodeAnalysis.CSharp;

namespace Proscenium.CodeQuality.Deslop;

// config/builtin.rs::built_in_report_hidden and has_generated_header.
internal static class DeslopVisibility
{
    public static bool IsHidden(DeslopFile file, string root)
    {
        var relativePath = Path.GetRelativePath(root, Path.Combine(root, file.Path));
        var parts = relativePath.Split(Path.DirectorySeparatorChar)
            .Select(LowerAscii).ToArray();
        return parts.Contains("generated", StringComparer.Ordinal)
            || s_hiddenPairs.Any(pair => ContainsPair(parts, pair))
            || s_hiddenSuffixes.Any(suffix => LowerAscii(Path.GetFileName(file.Path)).EndsWith(suffix, StringComparison.Ordinal))
            || HasGeneratedHeader(file);
    }

    private static bool ContainsPair(string[] parts, (string First, string Second) pair)
    {
        for (var index = 0; index + 1 < parts.Length; index++)
        {
            if (parts[index] == pair.First && parts[index + 1] == pair.Second)
            {
                return true;
            }
        }

        return false;
    }

    private static string LowerAscii(string text) => string.Create(text.Length,
        text,
        (chars, source) =>
    {
        for (var index = 0; index < source.Length; index++)
        {
            var value = source[index];
            chars[index] = value is >= 'A' and <= 'Z' ? (char)(value + ('a' - 'A')) : value;
        }
    });

    private static bool HasGeneratedHeader(DeslopFile file)
    {
        // Apply the byte limit before decoding, so Unicode and a UTF-8 BOM
        // consume their original space in the banner budget.
        var head = LowerAscii(Encoding.UTF8.GetString(file.Source, 0, Math.Min(file.Source.Length, 1024)));
        foreach (var trivia in file.SyntaxTree.GetRoot().GetLeadingTrivia())
        {
            var kind = (SyntaxKind)trivia.RawKind;
            if (kind is SyntaxKind.WhitespaceTrivia or SyntaxKind.EndOfLineTrivia)
                continue;
            if (kind is not (SyntaxKind.SingleLineCommentTrivia or SyntaxKind.MultiLineCommentTrivia
                or SyntaxKind.SingleLineDocumentationCommentTrivia or SyntaxKind.MultiLineDocumentationCommentTrivia))
                break;
            var start = trivia.SpanStart;
            var end = Math.Min(trivia.Span.End, head.Length);
            if (start >= end)
                break;
            var comment = head[start..end];
            if (s_headerMarkers.Any(marker => comment.Contains(marker, StringComparison.Ordinal)))
                return true;
        }
        return false;
    }

    private static readonly (string First, string Second)[] s_hiddenPairs =
        [("alembic", "versions"), ("test", "fixtures"), ("tests", "fixtures")];

    private static readonly string[] s_hiddenSuffixes =
        [".g.cs", ".generated.cs", ".designer.cs", ".pb.cs", ".openapi.cs"];

    private static readonly string[] s_headerMarkers =
        ["@generated", "generated code", "auto generated", "auto-generated", "autogenerated", "automatically generated"];
}
